domain: ecovibes.fr
url: "https://ecovibes.fr"
baseurl: ""
title: |
  EcoVibes - Produits éco-friendly et articles de blog pour un mode de vie
  durable

description: |
  Chez EcoVibes, trouvez une sélection de produits éco-friendly pour votre
  maison, votre cuisine, votre mode de vie et vos voyages. Découvrez également
  nos articles de blog sur les dernières tendances en matière d'écologie.
  Rejoignez notre communauté de passionnés de l'environnement et achetez avec
  EcoVibes aujourd'hui !

timezone: Europe/Paris

# Sass
sass:
 style: compact

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Responsive images
responsive:
  widths:
    - 480
    - 768
    - 1024

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-responsive-magick
  - jekyll-date-localization

# SEO
locale: fr_FR
social:

# Internationalization
date_locale: fr

collections:
  kinds:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
      type: kinds
    values:
      layout: category

  -
    scope:
      path: ""
    values:
      date_format: "%d %B %Y"

  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
